version: '3.8'

services:
  app:
    image: kotlin-app:latest
    container_name: kotlin-app
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo_db
      SPRING_DATASOURCE_USERNAME: demo_user
      SPRING_DATASOURCE_PASSWORD: demo_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
      POSTGRES_DB: demo_db
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
