apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t  # Base64 encoded 'admin@admin.com'
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4=          # Base64 encoded 'admin'
