apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: ZGVtb191c2Vy      # Base64-encoded 'demo_user'
  POSTGRES_PASSWORD: ZGVtb19wYXNzd29yZA==  # Base64-encoded 'demo_password'
  POSTGRES_DB: ZGVtb19kYg==         # Base64-encoded 'demo_db'
