apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USERNAME: ZGVtb191c2Vy  # Base64 encoded value of 'demo_user'
  DB_PASSWORD: ZGVtb19wYXNzd29yZA==  # Base64 encoded value of 'demo_password'
